# Generated by Django 3.0.6 on 2020-09-27 11:06

import datetime
import django.core.validators
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('杭州', (('yhq', '余杭区'), ('xsq', '萧山区'), ('bjq', '滨江区'), ('xhq', '西湖区'), ('gsq', '拱墅区'), ('jgq', '江干区'), ('xcq', '下城区'), ('scq', '上城区'))), ('嘉兴', (('hn', '海宁市'), ('tx', '桐乡市'), ('hy', '海盐县'), ('ph', '平湖市'), ('js', '嘉善县'), ('nhq', '南湖区'), ('xzq', '秀洲区'))), ('湖州', (('dq', '德清县'), ('nxq', '南浔区'), ('wxq', '吴兴区'), ('cx', '长兴县'))), ('苏州', (('wjq', '吴江区'),)), ('绍兴', (('vhs', '越城区'), ('dvd', '柯桥区'), ('syq', '上虞区'))), ('上海', (('jsq', '金山区'),))], default='hn', max_length=3)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('rating', models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='rating')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ('-date',),
            },
        ),
    ]
